version: '3'
services:
  freqtrade:
    image: freqtradeorg/freqtrade:stable
    restart: always
    container_name: chacal_bot
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      trade -v --logfile /freqtrade/user_data/logs/freqtrade.log --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite --config /freqtrade/user_data/config_chacal_aws.json --strategy EstrategiaChacal
